version: '3'

services:
  phpunit:
    image: devwithlando/php:7.4-fpm-2
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: phpunitdatabase
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
        - .:/app

  phpunitdatabase:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
