version: '3'

services:
  phpunit:
    image: devwithlando/php:7.4-fpm-2
    volumes:
        - .:/app

  phpunitdatabase:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
