import React from "react";
import renderer from "react-test-renderer";
import App from "../../includes/settings/js/src/App";

describe("App", () => {
	window.atlasContentModeler = {
		appPath: "/wp-admin/admin.php?page=atlas-content-modeler",
		taxonomies: {
			mutagen: {
				types: ["turtle", "rodent", "villain"],
				show_in_rest: true,
				show_in_graphql: true,
				hierarchical: false,
				api_visibility: "public",
				singular: "Mutagen",
				plural: "Mutagen",
				slug: "mutagen",
			},
			color: {
				types: ["turtle", "person"],
				show_in_rest: true,
				show_in_graphql: true,
				hierarchical: false,
				api_visibility: "private",
				singular: "Color",
				plural: "Colors",
				slug: "color",
			},
			actionfigure: {
				types: ["turtle", "rodent", "villain", "person"],
				show_in_rest: true,
				show_in_graphql: true,
				hierarchical: false,
				api_visibility: "private",
				singular: "Action Figure",
				plural: "Action Figures",
				slug: "actionfigure",
			},
			cartoon: {
				types: ["turtle", "rodent", "villain", "person"],
				show_in_rest: true,
				show_in_graphql: true,
				hierarchical: false,
				api_visibility: "private",
				singular: "Cartoon",
				plural: "Cartoons",
				slug: "cartoon",
			},
			sewercover: {
				types: ["city"],
				show_in_rest: true,
				show_in_graphql: true,
				hierarchical: false,
				api_visibility: "private",
				singular: "Sewer Cover",
				plural: "Sewer Covers",
				slug: "sewercover",
			},
			enemybeaten: {
				types: ["turtle", "rodent", "person"],
				show_in_rest: true,
				show_in_graphql: true,
				hierarchical: false,
				api_visibility: "private",
				singular: "Enemy Beaten",
				plural: "Enemies Beaten",
				slug: "enemybeaten",
			},
		},
		initialState: {
			turtle: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Turtle",
				plural: "Turtles",
				slug: "turtle",
				api_visibility: "private",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653423770482: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653423770482",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
					1653423782249: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653423782249",
						position: "10000",
						name: "Weapon",
						slug: "weapon",
						isRepeatable: false,
						inputType: "single",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
					1653423984657: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "relationship",
						id: "1653423984657",
						position: "20000",
						name: "Enemies",
						slug: "enemies",
						required: false,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
						reference: "villain",
						cardinality: "one-to-many",
						enableReverse: false,
						reverseName: "Turtles",
						reverseSlug: "turtles",
					},
					1653441290838: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "relationship",
						id: "1653441290838",
						position: "30000",
						name: "City",
						slug: "city",
						required: false,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
						reference: "city",
						cardinality: "many-to-one",
						enableReverse: false,
						reverseName: "Turtles",
						reverseSlug: "turtles",
					},
					1654525161428: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "number",
						id: "1654525161428",
						position: "40000",
						name: "Age",
						slug: "age",
						isRepeatableNumber: "false",
						numberType: "integer",
						required: true,
						description: "",
						minValue: 1,
						maxValue: 19,
						step: 3,
					},
					1654529641877: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "number",
						id: "1654529641877",
						position: "50000",
						name: "test",
						slug: "test",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
						isRepeatableNumber: "true",
						numberType: "integer",
						minValue: "",
						maxValue: "",
						step: "",
					},
				},
			},
			rodent: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Rodent",
				plural: "Rodents",
				slug: "rodent",
				api_visibility: "private",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653423812208: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653423812208",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
					1653423821682: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "relationship",
						id: "1653423821682",
						position: "10000",
						name: "Students",
						slug: "students",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
						reference: "turtle",
						cardinality: "one-to-many",
						enableReverse: false,
						reverseName: "Rodents",
						reverseSlug: "rodents",
					},
				},
			},
			food: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Food",
				plural: "Foods",
				slug: "food",
				api_visibility: "public",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653423850158: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653423850158",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
				},
				with_front: "1",
			},
			villain: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Villain",
				plural: "Villains",
				slug: "villain",
				api_visibility: "private",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653423940495: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653423940495",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
				},
			},
			person: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Person",
				plural: "People",
				slug: "person",
				api_visibility: "public",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653424388121: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653424388121",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
					1653424397223: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653424397223",
						position: "10000",
						name: "Position",
						slug: "position",
						isRepeatable: false,
						inputType: "single",
						required: true,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
				},
			},
			pizza: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Pizza",
				plural: "Pizzas",
				slug: "pizza",
				api_visibility: "public",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653440708906: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653440708906",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: false,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
				},
			},
			city: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "City",
				plural: "Cities",
				slug: "city",
				api_visibility: "public",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653441260533: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653441260533",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: false,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
				},
			},
			rat: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Rat",
				plural: "Rats",
				slug: "rat",
				api_visibility: "private",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: {
					1653443249775: {
						show_in_rest: true,
						show_in_graphql: true,
						type: "text",
						id: "1653443249775",
						position: "0",
						name: "Name",
						slug: "name",
						isRepeatable: false,
						isTitle: true,
						inputType: "single",
						required: false,
						description: "",
						minChars: "",
						maxChars: "",
						minRepeatable: "",
						maxRepeatable: "",
					},
				},
			},
			cheese: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Cheese",
				plural: "Cheeses",
				slug: "cheese",
				api_visibility: "private",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: [],
			},
			poo: {
				show_in_rest: true,
				show_in_graphql: true,
				singular: "Poo",
				plural: "Poos",
				slug: "poo",
				api_visibility: "private",
				model_icon: "dashicons-admin-post",
				description: "",
				fields: [],
				with_front: "1",
			},
		},
		isWPGraphQLActive: "",
		isGraphiQLAvailable: "",
		graphQLUrl: "http://localhost:10003/graphql",
		usageTrackingEnabled: "",
		stats: {
			modelsCounts: [
				{
					model: "rat",
					count: "16",
					plural: "Rats",
				},
				{
					model: "villain",
					count: "10",
					plural: "Villains",
				},
				{
					model: "pizza",
					count: "10",
					plural: "Pizzas",
				},
				{
					model: "turtle",
					count: "8",
					plural: "Turtles",
				},
				{
					model: "person",
					count: "6",
					plural: "People",
				},
				{
					model: "city",
					count: "2",
					plural: "Cities",
				},
				{
					model: "rodent",
					count: "2",
					plural: "Rodents",
				},
				{
					model: "cheese",
					count: "1",
					plural: "Cheeses",
				},
			],
			recentModelEntries: [
				{
					ID: 381,
					post_author: "1",
					post_date: "2022-05-25 01:49:48",
					post_date_gmt: "2022-05-25 01:49:48",
					post_content: "",
					post_title: "The Rat King",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "the-rat-king",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:49:48",
					post_modified_gmt: "2022-05-25 01:49:48",
					post_content_filtered: "",
					post_parent: 0,
					guid:
						"http://localhost:10003/?post_type=villain&#038;p=381",
					menu_order: 0,
					post_type: "villain",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 470,
					post_author: "1",
					post_date: "2022-05-25 01:49:48",
					post_date_gmt: "2022-05-25 01:49:48",
					post_content: "",
					post_title: "The Rat King",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "the-rat-king-2",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:49:48",
					post_modified_gmt: "2022-05-25 01:49:48",
					post_content_filtered: "",
					post_parent: 0,
					guid:
						"http://localhost:10003/posts/villain/the-rat-king-2/",
					menu_order: 0,
					post_type: "villain",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 380,
					post_author: "1",
					post_date: "2022-05-25 01:48:27",
					post_date_gmt: "2022-05-25 01:48:27",
					post_content: "",
					post_title: "Bartholomew",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "bartholomew",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:27",
					post_modified_gmt: "2022-05-25 01:48:27",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/?post_type=rat&#038;p=380",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 471,
					post_author: "1",
					post_date: "2022-05-25 01:48:27",
					post_date_gmt: "2022-05-25 01:48:27",
					post_content: "",
					post_title: "Bartholomew",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "bartholomew-2",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:27",
					post_modified_gmt: "2022-05-25 01:48:27",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/posts/rat/bartholomew-2/",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 472,
					post_author: "1",
					post_date: "2022-05-25 01:48:19",
					post_date_gmt: "2022-05-25 01:48:19",
					post_content: "",
					post_title: "Susan",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "susan-2",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:19",
					post_modified_gmt: "2022-05-25 01:48:19",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/posts/rat/susan-2/",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 379,
					post_author: "1",
					post_date: "2022-05-25 01:48:19",
					post_date_gmt: "2022-05-25 01:48:19",
					post_content: "",
					post_title: "Susan",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "susan",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:19",
					post_modified_gmt: "2022-05-25 01:48:19",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/?post_type=rat&#038;p=379",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 378,
					post_author: "1",
					post_date: "2022-05-25 01:48:12",
					post_date_gmt: "2022-05-25 01:48:12",
					post_content: "",
					post_title: "Bentley",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "bentley",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:12",
					post_modified_gmt: "2022-05-25 01:48:12",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/?post_type=rat&#038;p=378",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 473,
					post_author: "1",
					post_date: "2022-05-25 01:48:12",
					post_date_gmt: "2022-05-25 01:48:12",
					post_content: "",
					post_title: "Bentley",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "bentley-2",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:12",
					post_modified_gmt: "2022-05-25 01:48:12",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/posts/rat/bentley-2/",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 474,
					post_author: "1",
					post_date: "2022-05-25 01:48:04",
					post_date_gmt: "2022-05-25 01:48:04",
					post_content: "",
					post_title: "Juju",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "juju-2",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:04",
					post_modified_gmt: "2022-05-25 01:48:04",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/posts/rat/juju-2/",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
				{
					ID: 377,
					post_author: "1",
					post_date: "2022-05-25 01:48:04",
					post_date_gmt: "2022-05-25 01:48:04",
					post_content: "",
					post_title: "Juju",
					post_excerpt: "",
					post_status: "publish",
					comment_status: "closed",
					ping_status: "closed",
					post_password: "",
					post_name: "juju",
					to_ping: "",
					pinged: "",
					post_modified: "2022-05-25 01:48:04",
					post_modified_gmt: "2022-05-25 01:48:04",
					post_content_filtered: "",
					post_parent: 0,
					guid: "http://localhost:10003/?post_type=rat&#038;p=377",
					menu_order: 0,
					post_type: "rat",
					post_mime_type: "",
					comment_count: "0",
					filter: "raw",
				},
			],
			relationships: {
				totalRelationshipConnections: 48,
				mostConnectedEntries: [
					{
						id1: "357",
						id2: "353",
						total_connections: "4",
						post_type: "rodent",
						post_title: "Splinter",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=357&action=edit",
					},
					{
						id1: "492",
						id2: "493",
						total_connections: "4",
						post_type: "rodent",
						post_title: "Splinter",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=492&action=edit",
					},
					{
						id1: "372",
						id2: "353",
						total_connections: "4",
						post_type: "city",
						post_title: "New York",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=372&action=edit",
					},
					{
						id1: "479",
						id2: "493",
						total_connections: "4",
						post_type: "city",
						post_title: "New York",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=479&action=edit",
					},
					{
						id1: "353",
						id2: "357",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Leonardo",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=353&action=edit",
					},
					{
						id1: "493",
						id2: "479",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Donatello",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=493&action=edit",
					},
					{
						id1: "354",
						id2: "357",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Michaelangelo",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=354&action=edit",
					},
					{
						id1: "494",
						id2: "479",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Rafael",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=494&action=edit",
					},
					{
						id1: "355",
						id2: "357",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Rafael",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=355&action=edit",
					},
					{
						id1: "495",
						id2: "479",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Michaelangelo",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=495&action=edit",
					},
					{
						id1: "356",
						id2: "357",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Donatello",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=356&action=edit",
					},
					{
						id1: "496",
						id2: "479",
						total_connections: "3",
						post_type: "turtle",
						post_title: "Leonardo",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=496&action=edit",
					},
					{
						id1: "489",
						id2: "494",
						total_connections: "1",
						post_type: "villain",
						post_title: "Shredder",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=489&action=edit",
					},
					{
						id1: "358",
						id2: "353",
						total_connections: "1",
						post_type: "villain",
						post_title: "Bebop",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=358&action=edit",
					},
					{
						id1: "490",
						id2: "495",
						total_connections: "1",
						post_type: "villain",
						post_title: "Rocksteady",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=490&action=edit",
					},
					{
						id1: "359",
						id2: "354",
						total_connections: "1",
						post_type: "villain",
						post_title: "Rocksteady",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=359&action=edit",
					},
					{
						id1: "491",
						id2: "496",
						total_connections: "1",
						post_type: "villain",
						post_title: "Bebop",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=491&action=edit",
					},
					{
						id1: "360",
						id2: "355",
						total_connections: "1",
						post_type: "villain",
						post_title: "Shredder",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=360&action=edit",
					},
					{
						id1: "361",
						id2: "356",
						total_connections: "1",
						post_type: "villain",
						post_title: "Krang",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=361&action=edit",
					},
					{
						id1: "488",
						id2: "493",
						total_connections: "1",
						post_type: "villain",
						post_title: "Krang",
						admin_link:
							"http://localhost:10003/wp-admin/post.php?post=488&action=edit",
					},
				],
			},
			taxonomies: {
				mutagen: {
					total_terms: "1",
					terms: [
						{
							term_id: 4,
							name: "Radioactive Ooze",
							slug: "ooze",
							term_group: 0,
							term_taxonomy_id: 4,
							taxonomy: "mutagen",
							description:
								"Radioactive slime that mutated the turtles",
							parent: 0,
							count: 8,
							filter: "raw",
							term_link:
								"http://localhost:10003/posts/mutagen/ooze/",
							admin_link:
								"http://localhost:10003/wp-admin/term.php?taxonomy&tag_ID=4&post_type=turtle",
						},
					],
				},
				color: {
					total_terms: "5",
					terms: [
						{
							term_id: 5,
							name: "Red",
							slug: "red",
							term_group: 0,
							term_taxonomy_id: 5,
							taxonomy: "color",
							description: "",
							parent: 0,
							count: 2,
							filter: "raw",
							term_link:
								"http://localhost:10003/posts/color/red/",
							admin_link:
								"http://localhost:10003/wp-admin/term.php?taxonomy&tag_ID=5&post_type=turtle",
						},
						{
							term_id: 6,
							name: "Yellow",
							slug: "yellow",
							term_group: 0,
							term_taxonomy_id: 6,
							taxonomy: "color",
							description: "",
							parent: 0,
							count: 2,
							filter: "raw",
							term_link:
								"http://localhost:10003/posts/color/yellow/",
							admin_link:
								"http://localhost:10003/wp-admin/term.php?taxonomy&tag_ID=6&post_type=turtle",
						},
						{
							term_id: 7,
							name: "Blue",
							slug: "blue",
							term_group: 0,
							term_taxonomy_id: 7,
							taxonomy: "color",
							description: "",
							parent: 0,
							count: 2,
							filter: "raw",
							term_link:
								"http://localhost:10003/posts/color/blue/",
							admin_link:
								"http://localhost:10003/wp-admin/term.php?taxonomy&tag_ID=7&post_type=turtle",
						},
						{
							term_id: 8,
							name: "Purple",
							slug: "purple",
							term_group: 0,
							term_taxonomy_id: 8,
							taxonomy: "color",
							description: "",
							parent: 0,
							count: 2,
							filter: "raw",
							term_link:
								"http://localhost:10003/posts/color/purple/",
							admin_link:
								"http://localhost:10003/wp-admin/term.php?taxonomy&tag_ID=8&post_type=turtle",
						},
						{
							term_id: 9,
							name: "Orange",
							slug: "orange",
							term_group: 0,
							term_taxonomy_id: 9,
							taxonomy: "color",
							description: "",
							parent: 0,
							count: 2,
							filter: "raw",
							term_link:
								"http://localhost:10003/posts/color/orange/",
							admin_link:
								"http://localhost:10003/wp-admin/term.php?taxonomy&tag_ID=9&post_type=turtle",
						},
					],
				},
				actionfigure: {
					total_terms: "0",
					terms: [],
				},
				cartoon: {
					total_terms: "0",
					terms: [],
				},
				sewercover: {
					total_terms: "0",
					terms: [],
				},
				enemybeaten: {
					total_terms: "0",
					terms: [],
				},
			},
		},
		acm_plugin_data: {
			Name: "Atlas Content Modeler",
			PluginURI: "https://developers.wpengine.com/",
			Version: "0.18.0",
			Description:
				'Model content for headless WordPress. <cite>By <a href="https://wpengine.com/">WP Engine</a>.</cite>',
			Author: '<a href="https://wpengine.com/">WP Engine</a>',
			AuthorURI: "https://wpengine.com/",
			TextDomain: "atlas-content-modeler",
			DomainPath: "/languages",
			Network: false,
			RequiresWP: "5.7",
			RequiresPHP: "7.2",
			UpdateURI: "",
			Title:
				'<a href="https://developers.wpengine.com/">Atlas Content Modeler</a>',
			AuthorName: "WP Engine",
		},
	};

	const app = renderer.create(<App />);

	let tree = app.toJSON();

	it("Renders a matching snapshot", () => {
		expect(tree).toMatchSnapshot();
	});
});
